version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

docker_hub_authentification: &docker_hub_authentification
  username: $DOCKERHUB_USER
  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        auth: *docker_hub_authentification
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements.txt"}}
      - run:
          name: Build, upgrade pip and install Python requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: venv-{{ checksum "requirements.txt"}}
          paths:
            - "venv"
  test:
    docker:
      - image: cimg/python:3.8
        auth: *docker_hub_authentification
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements.txt"}}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  flake8:
    docker:
      - image: cimg/python:3.8
        auth: *docker_hub_authentification
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements.txt"}}
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            flake8 

  package:
    docker:
      - image: cimg/python:3.8
        auth: *docker_hub_authentification
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build container
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
            docker build -t $DOCKERHUB_USER/oc_lettings:latest .
      - run:
          name: Push container to Dockerhub
          command: |
            docker push $DOCKERHUB_USER/oc_lettings:latest

  deploy: # this can be any name you choose
      executor: heroku/default # use the default executor defined within the orb
      docker:
      - image: cimg/python:3.8
        auth: *docker_hub_authentification
      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
        - run:
            name: Pull container from Dockerhub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
              docker pull $DOCKERHUB_USER/oc_lettings:latest
        - run:
            name: Install Heroku CLI
            command: |
              curl https://cli-assets.heroku.com/install.sh | sh
        - run:
            name: Push container to Heroku
            command: |
              heroku container:login
              heroku git:remote -a $HEROKU_APP_NAME
              heroku container:push web
              heroku container:release web

# Orchestrate our job run sequence
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build
      - flake8:
          requires:
            - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
            - flake8
          filters:
            branches:
              only: master # only deploy when on master branch
      - deploy:
          requires:
            - package # only deploy if the package job has completed
          filters:
            branches:
              only: master # only deploy when on master branch


