# Generated by Django 3.0 on 2022-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20220517_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
