# Generated by Django 3.0 on 2022-05-17 11:28

from django.db import migrations

def move_profiles(apps, schema_editor):

    OldProfile = apps.get_model('config', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    objs = OldProfile.objects.all()
    NewProfile.objects.bulk_create(objs)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_profiles, migrations.RunPython.noop),
    ]
